---
author: "[Nate Edgar](https://github.com/Nateedgar97)"
subtitle: 'Daily Exercise 16: Creating a Function'
output:
  html_document:
    theme: journal
---

# Libraries

### SPDS
```{r, message=FALSE}
library(tidyverse)
library(sf)
library(units)
```

### Data
```{r, message=FALSE}
library(USAboundaries)
library(rnaturalearth)
```

### Visualization
```{r, message=FALSE}
library(gghighlight)
library(ggrepel)
library(ggthemes)
library(knitr)
library(kableExtra)
library(leaflet)
library(readxl)
```

## Question 1: 

#### Step 1.1
```{r, message=FALSE, warning=FALSE}
majorrivers = read_sf("../data/MajorRivers.dbf") %>% 
  filter(SYSTEM == "Mississippi") %>%
  mutate(STATE = c("AR", "MI", "MO", "OH")) %>% 
  st_transform(4326)
```

#### Step 1.2
```{r, message=FALSE, warning=FALSE}
dams_of_interest = read_xlsx("../data/NID2019_U.xlsx") %>% 
  filter(!is.na(LATITUDE)) %>% 
  filter(grepl("H", PURPOSES)) %>%
  filter(DAM_NAME != "SOO LOCKS") %>% 
  select(DAM_NAME, PURPOSES, NID_STORAGE, YEAR_COMPLETED, STATE, LONGITUDE, LATITUDE) %>% 
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs=4326) %>%
  st_transform(st_crs(majorrivers)) %>% 
  group_by(STATE) %>% 
  slice_max(NID_STORAGE, n=1) %>% 
  ungroup()
```

#### Step 1.3
```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  addPolylines(data = majorrivers) %>% 
  addCircleMarkers(data = dams_of_interest,
             fillColor  = ~colorQuantile("YlOrRd", NID_STORAGE)(NID_STORAGE),
             color = NA,
             fillOpacity = .5,
             radius = ~NID_STORAGE / 1500000,
             label = ~DAM_NAME,
             popup = leafpop::popupTable(st_drop_geometry(dams_of_interest), feature.id = FALSE, row.numbers = FALSE)) %>% 
  addMeasure() %>% 
  leafem::addMouseCoordinates()
```





