---
title: "Geography 176A"
author: "[Nate Edgar](https://github.com/Nateedgar97)"
subtitle: 'Lab 04: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---

# Libraries

### SPDS
```{r, message=FALSE}
library(tidyverse)
library(sf)
library(units)
```

### Data
```{r, message=FALSE}
library(USAboundaries)
library(rnaturalearth)
```

### Visualization
```{r, message=FALSE}
library(gghighlight)
library(ggrepel)
library(ggthemes)
library(knitr)
library(kableExtra)
```

## Question 1: Tesselation of Surfaces

#### Step 1.1
Getting CONUS States
```{r}
conus = USAboundaries::us_counties() %>% 
  filter(!state_name %in% c("Hawaii", "Puerto Rico", "Alaska",
             "Guam", "District of Columbia")) %>% 
  st_transform(5070)
```
 
#### Step 1.2
```{r}
conus_cent = conus %>% 
  st_centroid() %>% 
  st_combine()
```
#### Test Function
```{r}

```


#### Step 1.3 & Step 1.4 & 1.5
```{r}
conus_vor = conus_cent %>% #1.3
  st_voronoi() %>% 
  st_cast() %>% 
  st_as_sf() %>%
  mutate(id = 1:n()) %>% 
  st_union() %>%           #1.4
  st_intersection(., conus) %>% 
  ms_simplify(keep = .05)   #1.5
  
conus_tri = conus_cent %>% 
  st_triangulate() %>% 
  st_cast() %>% 
  st_as_sf() %>%
  mutate(id = 1:n()) %>% 
  st_union() %>% 
  st_intersection(., conus) %>% 
  ms_simplify(keep = .1)

conus_grd = conus_cent %>% 
  st_make_grid(n = c(70,70)) %>% 
  st_cast() %>% 
  st_as_sf() %>%
  mutate(id = 1:n()) %>% 
  st_union() %>% {sf}	
  st_intersection(., conus) %>% 
  ms_simplify(keep = .1)

conus_hex = conus_cent %>% 
  st_make_grid(n = c(70,70), square = FALSE) %>% 
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n()) %>% 
  st_union %>% 
  st_intersection(., conus) %>% 
  ms_simplify(keep = .05)
```

#### Step 1.6 - FUNCTION JUNCTION
```{r}
plot_tes = function(arg1, title){
  ggplot() + 
    geom_sf(data = arg1, col = "white", size = .2) + 
    theme_void() + 
    theme(legend.position = 'none',
          plot.title = element_text(face = "bold", color = "darkblue", hjust = .5, size = 24)) +
    labs(title = paste0(title),
         caption = paste0(mapview::npts(arg1), " features"))
}
```

#### Step 1.7
```{r}
plot_tes(conus, "Original")
plot_tes(conus_vor, "Voroni")
plot_tes(conus_tri, "Triangualtion")
plot_tes(conus_grd, "Square")
plot_tes(conus_hex, "Hexegonal")
```
